### PR TITLE
Add a custom parser for matrix names

### PR DESCRIPTION
**Pull request by mfasi**
In some cases, matrix names cannot be valid MATLAB function names. For example,
a matrix name may need to start with numbers. With this change, group developers
can ship a custom function in
```
<group_name>/private/anymatrix_parse_<group_name>.m
```
to perform any name transformations that are required.

### CODE REVIEW

**Comment by mmikaitis** [comment]
Many thanks for your suggested improvement. One issue that can possibly arise is matrix name clashes. Currently this is not possible because matrix names are derived from the matrix M-file names, however, with the proposed approach a user may specify same ID being mapped from two different file names, if I understand this correctly. Does anymatrix need to check for this or is it up to users' mapping functions to assure one to one mapping of file names to matrix names?

**Comment by mfasi** [comment]
I had not thought about that, probably because I'm using the functionality in a rather straightforward fashion. I have some matrix IDs that start with a number, and I simply prepend to all matrix IDs the string `<group_name>_`, which the parser then removes.

I would leave this to the group developer to fix, although I think it would be possible to modify the `scan_matrices` function to check whether a new ID is already present in the `IDs` cell array before inserting. The function would then throw an error when trying to insert an ID which is already present.

**Comment by mmikaitis** [comment]
I think we will shelve this feature for now as a possible future improvement. For now we can try to restructure your new group to follow the current naming rules, where matrix M-file/function names = matrix names, group folder names = group names.

**Comment by mfasi** [comment]
Thanks for looking at the pull request. Changing the name of the problematic matrices in my group so that they are valid MATLAB functions would certainly be possible.

To give a bit more context, the problem I'm having is with some matrices in the [Suite Sparse Matrix Collection](http://sparse.tamu.edu/). I would like the Anymatrix interface to behave as similarly as possible to the [`ssget`](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/ssget/ssget.m) interface to the collection, where you can simply type
```MATLAB
ssget('HB/1138_bus')
```
to get the corresponding matrix (in fact, you get a structure whose `A` field is the matrix). Without this patch, we need to change the matrix name to, for example, `hb_1138_bus`, and then do
```MATLAB
anymatrix('HB/hb_1138_bus')
```
This is certainly possible, but would not be ideal as it would change the matrix name users are used to.

Perhaps, as my only use case for the parser is that of matrix names starting with a number, one could hard-code this simpler case in Anymatrix and just add a rule that says: "if the `matrix_ID` starts with a number, then add a certain dummy string to it in order to get the generator name, and if a function name starts with that dummy string, then `anymatrix('g', <group_name>)` should display the `matrix_ID` without it".

I can make the corresponding repository public if you'd like to have a look—perhaps you can find an alternative that works without changing Anymatrix. This comes with the caveat that the collection only works, bugs notwithstanding, with the `custom_matrix_name_parser` branch of [my fork](https://github.com/mfasi/anymatrix) of Anymatrix.

Either way, I'll close this pull request for now to avoid cluttering the PR tab.

**Pull request closed without merging**
